from pathlib import Path

# Files
ROOT_DIR = Path(__file__).parent
FILES_PATH = ROOT_DIR / 'files'
ICON_PATH =  FILES_PATH / 'icon.png'

# Sizing
BIG_FONT_SIZE = 40
MEDIUM_FONT_SIZE = 24
SMALL_FONT_SIZE = 18
TEXT_MARGIN = 15
MININUM_WIDTH = 500

# Theme colors
DARKER_PRIMARY_COLOR = '#1e81b0'
DARKEST_PRIMARY_COLOR = '#16658a'
PRIMARY_COLOR = '#115270'